version: '3.8'

services:
  mysqldb:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Sung2708@
      - MYSQL_DATABASE=online_academy
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  app:
    volumes:
    - ./src:/src
    depends_on:
      - mysqldb
    build: ./src
    restart: always
    ports:
      - 3000:3000
    environment:
      - DB_HOST=localhost
      - DB_USER=root
      - DB_PASSWORD=Sung2708@
      - DB_NAME=online_academy
    stdin_open: true
    tty: true

volumes: 
  db: